behaviors:
  Drecon:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 4
      vis_encode_type: simple
      init_near_zero: true
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
            num_layers: 4
            normalize: true
    keep_checkpoints: 10
    max_steps: 300000000
    checkpoint_interval: 200000 
    time_horizon: 64
    summary_freq: 100000
    threaded: true
