behaviors:
  Drecon:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2000
      buffer_size: 40000
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: True
    keep_checkpoints: 10
    max_steps: 300000000
    checkpoint_interval: 500000 
    time_horizon: 240
    summary_freq: 100000
